let ff = {
  location: {
    name: "Fergana",
    region: "Farghona",
    country: "Uzbekistan",
    lat: 40.39,
    lon: 71.78,
    tz_id: "Asia/Tashkent",
    localtime_epoch: 1672417017,
    localtime: "2022-12-30 21:16"
  },
  current: {
    last_updated_epoch: 1672416900,
    last_updated: "2022-12-30 21:15",
    temp_c: 3,
    temp_f: 37.4,
    is_day: 0,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
      code: 1003
    },
    wind_mph: 2.2,
    wind_kph: 3.6,
    wind_degree: 99,
    wind_dir: "E",
    pressure_mb: 1035,
    pressure_in: 30.56,
    precip_mm: 0,
    precip_in: 0,
    humidity: 69,
    cloud: 29,
    feelslike_c: 2.7,
    feelslike_f: 36.9,
    vis_km: 10,
    vis_miles: 6,
    uv: 1,
    gust_mph: 3.6,
    gust_kph: 5.8
  },
  forecast: {
    forecastday: [
      {
        date: "2022-12-30",
        date_epoch: 1672358400,
        day: {
          maxtemp_c: 6.2,
          maxtemp_f: 43.2,
          mintemp_c: 0.2,
          mintemp_f: 32.4,
          avgtemp_c: 3,
          avgtemp_f: 37.4,
          maxwind_mph: 5.1,
          maxwind_kph: 8.3,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 70,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003
          },
          uv: 2
        },
        astro: {
          sunrise: "07:36 AM",
          sunset: "04:55 PM",
          moonrise: "12:18 PM",
          moonset: "No moonset",
          moon_phase: "First Quarter",
          moon_illumination: "47"
        },
        hour: [
          {
            time_epoch: 1672340400,
            time: "2022-12-30 00:00",
            temp_c: 2.6,
            temp_f: 36.7,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 77,
            wind_dir: "ENE",
            pressure_mb: 1033,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 99,
            feelslike_c: 0.2,
            feelslike_f: 32.4,
            windchill_c: 0.2,
            windchill_f: 32.4,
            heatindex_c: 2.6,
            heatindex_f: 36.7,
            dewpoint_c: -2.5,
            dewpoint_f: 27.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.7,
            gust_kph: 14,
            uv: 1
          },
          {
            time_epoch: 1672344000,
            time: "2022-12-30 01:00",
            temp_c: 2.4,
            temp_f: 36.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 54,
            wind_dir: "NE",
            pressure_mb: 1034,
            pressure_in: 30.52,
            precip_mm: 0,
            precip_in: 0,
            humidity: 71,
            cloud: 46,
            feelslike_c: 0.3,
            feelslike_f: 32.5,
            windchill_c: 0.3,
            windchill_f: 32.5,
            heatindex_c: 2.4,
            heatindex_f: 36.3,
            dewpoint_c: -2.2,
            dewpoint_f: 28,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1
          },
          {
            time_epoch: 1672347600,
            time: "2022-12-30 02:00",
            temp_c: 1.7,
            temp_f: 35.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 29,
            wind_dir: "NNE",
            pressure_mb: 1034,
            pressure_in: 30.54,
            precip_mm: 0,
            precip_in: 0,
            humidity: 75,
            cloud: 45,
            feelslike_c: -0.1,
            feelslike_f: 31.8,
            windchill_c: -0.1,
            windchill_f: 31.8,
            heatindex_c: 1.7,
            heatindex_f: 35.1,
            dewpoint_c: -2.2,
            dewpoint_f: 28,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1
          },
          {
            time_epoch: 1672351200,
            time: "2022-12-30 03:00",
            temp_c: 1,
            temp_f: 33.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 17,
            wind_dir: "NNE",
            pressure_mb: 1035,
            pressure_in: 30.57,
            precip_mm: 0,
            precip_in: 0,
            humidity: 79,
            cloud: 60,
            feelslike_c: -0.3,
            feelslike_f: 31.5,
            windchill_c: -0.3,
            windchill_f: 31.5,
            heatindex_c: 1,
            heatindex_f: 33.8,
            dewpoint_c: -2.3,
            dewpoint_f: 27.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 1
          },
          {
            time_epoch: 1672354800,
            time: "2022-12-30 04:00",
            temp_c: 0.9,
            temp_f: 33.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 25,
            wind_dir: "NNE",
            pressure_mb: 1036,
            pressure_in: 30.58,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 41,
            feelslike_c: 0.2,
            feelslike_f: 32.4,
            windchill_c: 0.2,
            windchill_f: 32.4,
            heatindex_c: 0.9,
            heatindex_f: 33.6,
            dewpoint_c: -1.9,
            dewpoint_f: 28.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 1
          },
          {
            time_epoch: 1672358400,
            time: "2022-12-30 05:00",
            temp_c: 0.6,
            temp_f: 33.1,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 42,
            wind_dir: "NE",
            pressure_mb: 1036,
            pressure_in: 30.59,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 21,
            feelslike_c: 0.6,
            feelslike_f: 33.1,
            windchill_c: 0.6,
            windchill_f: 33.1,
            heatindex_c: 0.6,
            heatindex_f: 33.1,
            dewpoint_c: -1.7,
            dewpoint_f: 28.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.9,
            gust_kph: 4.7,
            uv: 1
          },
          {
            time_epoch: 1672362000,
            time: "2022-12-30 06:00",
            temp_c: 0.3,
            temp_f: 32.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 73,
            wind_dir: "ENE",
            pressure_mb: 1036,
            pressure_in: 30.6,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 56,
            feelslike_c: 0.3,
            feelslike_f: 32.5,
            windchill_c: 0.3,
            windchill_f: 32.5,
            heatindex_c: 0.3,
            heatindex_f: 32.5,
            dewpoint_c: -1.7,
            dewpoint_f: 28.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.2,
            gust_kph: 3.6,
            uv: 1
          },
          {
            time_epoch: 1672365600,
            time: "2022-12-30 07:00",
            temp_c: 0.2,
            temp_f: 32.4,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 95,
            wind_dir: "E",
            pressure_mb: 1037,
            pressure_in: 30.61,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 64,
            feelslike_c: 0.2,
            feelslike_f: 32.4,
            windchill_c: 0.2,
            windchill_f: 32.4,
            heatindex_c: 0.2,
            heatindex_f: 32.4,
            dewpoint_c: -1.6,
            dewpoint_f: 29.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.2,
            gust_kph: 3.6,
            uv: 1
          },
          {
            time_epoch: 1672369200,
            time: "2022-12-30 08:00",
            temp_c: 0.4,
            temp_f: 32.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 0.4,
            wind_kph: 0.7,
            wind_degree: 162,
            wind_dir: "SSE",
            pressure_mb: 1037,
            pressure_in: 30.62,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 50,
            feelslike_c: 0.4,
            feelslike_f: 32.7,
            windchill_c: 0.4,
            windchill_f: 32.7,
            heatindex_c: 0.4,
            heatindex_f: 32.7,
            dewpoint_c: -2.5,
            dewpoint_f: 27.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.9,
            gust_kph: 1.4,
            uv: 2
          },
          {
            time_epoch: 1672372800,
            time: "2022-12-30 09:00",
            temp_c: 1.8,
            temp_f: 35.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 0.2,
            wind_kph: 0.4,
            wind_degree: 271,
            wind_dir: "W",
            pressure_mb: 1037,
            pressure_in: 30.62,
            precip_mm: 0,
            precip_in: 0,
            humidity: 75,
            cloud: 34,
            feelslike_c: 1.8,
            feelslike_f: 35.2,
            windchill_c: 1.8,
            windchill_f: 35.2,
            heatindex_c: 1.8,
            heatindex_f: 35.2,
            dewpoint_c: -2.1,
            dewpoint_f: 28.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.4,
            gust_kph: 0.7,
            uv: 2
          },
          {
            time_epoch: 1672376400,
            time: "2022-12-30 10:00",
            temp_c: 3,
            temp_f: 37.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 347,
            wind_dir: "NNW",
            pressure_mb: 1037,
            pressure_in: 30.62,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 27,
            feelslike_c: 3,
            feelslike_f: 37.4,
            windchill_c: 3,
            windchill_f: 37.4,
            heatindex_c: 3,
            heatindex_f: 37.4,
            dewpoint_c: -2.2,
            dewpoint_f: 28,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.5,
            gust_kph: 4,
            uv: 2
          },
          {
            time_epoch: 1672380000,
            time: "2022-12-30 11:00",
            temp_c: 4.2,
            temp_f: 39.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 355,
            wind_dir: "N",
            pressure_mb: 1037,
            pressure_in: 30.61,
            precip_mm: 0,
            precip_in: 0,
            humidity: 64,
            cloud: 21,
            feelslike_c: 3.2,
            feelslike_f: 37.8,
            windchill_c: 3.2,
            windchill_f: 37.8,
            heatindex_c: 4.2,
            heatindex_f: 39.6,
            dewpoint_c: -1.9,
            dewpoint_f: 28.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.1,
            uv: 2
          },
          {
            time_epoch: 1672383600,
            time: "2022-12-30 12:00",
            temp_c: 4.9,
            temp_f: 40.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 356,
            wind_dir: "N",
            pressure_mb: 1036,
            pressure_in: 30.59,
            precip_mm: 0,
            precip_in: 0,
            humidity: 61,
            cloud: 19,
            feelslike_c: 4.1,
            feelslike_f: 39.4,
            windchill_c: 4.1,
            windchill_f: 39.4,
            heatindex_c: 4.9,
            heatindex_f: 40.8,
            dewpoint_c: -2,
            dewpoint_f: 28.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 2
          },
          {
            time_epoch: 1672387200,
            time: "2022-12-30 13:00",
            temp_c: 5.7,
            temp_f: 42.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 5,
            wind_dir: "N",
            pressure_mb: 1035,
            pressure_in: 30.57,
            precip_mm: 0,
            precip_in: 0,
            humidity: 57,
            cloud: 20,
            feelslike_c: 5.7,
            feelslike_f: 42.3,
            windchill_c: 5.7,
            windchill_f: 42.3,
            heatindex_c: 5.7,
            heatindex_f: 42.3,
            dewpoint_c: -2,
            dewpoint_f: 28.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2,
            gust_kph: 3.2,
            uv: 3
          },
          {
            time_epoch: 1672390800,
            time: "2022-12-30 14:00",
            temp_c: 5.9,
            temp_f: 42.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 48,
            wind_dir: "NE",
            pressure_mb: 1035,
            pressure_in: 30.57,
            precip_mm: 0,
            precip_in: 0,
            humidity: 57,
            cloud: 17,
            feelslike_c: 5.9,
            feelslike_f: 42.6,
            windchill_c: 5.9,
            windchill_f: 42.6,
            heatindex_c: 5.9,
            heatindex_f: 42.6,
            dewpoint_c: -2,
            dewpoint_f: 28.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2,
            gust_kph: 3.2,
            uv: 3
          },
          {
            time_epoch: 1672394400,
            time: "2022-12-30 15:00",
            temp_c: 6.2,
            temp_f: 43.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 45,
            wind_dir: "NE",
            pressure_mb: 1035,
            pressure_in: 30.57,
            precip_mm: 0,
            precip_in: 0,
            humidity: 56,
            cloud: 15,
            feelslike_c: 6.2,
            feelslike_f: 43.2,
            windchill_c: 6.2,
            windchill_f: 43.2,
            heatindex_c: 6.2,
            heatindex_f: 43.2,
            dewpoint_c: -2,
            dewpoint_f: 28.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2,
            gust_kph: 3.2,
            uv: 3
          },
          {
            time_epoch: 1672398000,
            time: "2022-12-30 16:00",
            temp_c: 6,
            temp_f: 42.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 31,
            wind_dir: "NNE",
            pressure_mb: 1035,
            pressure_in: 30.57,
            precip_mm: 0,
            precip_in: 0,
            humidity: 59,
            cloud: 15,
            feelslike_c: 6,
            feelslike_f: 42.8,
            windchill_c: 6,
            windchill_f: 42.8,
            heatindex_c: 6,
            heatindex_f: 42.8,
            dewpoint_c: -1.4,
            dewpoint_f: 29.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.8,
            gust_kph: 2.9,
            uv: 3
          },
          {
            time_epoch: 1672401600,
            time: "2022-12-30 17:00",
            temp_c: 4.4,
            temp_f: 39.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 8,
            wind_dir: "N",
            pressure_mb: 1035,
            pressure_in: 30.58,
            precip_mm: 0,
            precip_in: 0,
            humidity: 65,
            cloud: 20,
            feelslike_c: 4.4,
            feelslike_f: 39.9,
            windchill_c: 4.4,
            windchill_f: 39.9,
            heatindex_c: 4.4,
            heatindex_f: 39.9,
            dewpoint_c: -1.7,
            dewpoint_f: 28.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.9,
            gust_kph: 4.7,
            uv: 1
          },
          {
            time_epoch: 1672405200,
            time: "2022-12-30 18:00",
            temp_c: 4,
            temp_f: 39.2,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 36,
            wind_dir: "NE",
            pressure_mb: 1035,
            pressure_in: 30.58,
            precip_mm: 0,
            precip_in: 0,
            humidity: 66,
            cloud: 28,
            feelslike_c: 4,
            feelslike_f: 39.2,
            windchill_c: 4,
            windchill_f: 39.2,
            heatindex_c: 4,
            heatindex_f: 39.2,
            dewpoint_c: -1.7,
            dewpoint_f: 28.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.8,
            gust_kph: 2.9,
            uv: 1
          },
          {
            time_epoch: 1672408800,
            time: "2022-12-30 19:00",
            temp_c: 3.8,
            temp_f: 38.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 71,
            wind_dir: "ENE",
            pressure_mb: 1036,
            pressure_in: 30.58,
            precip_mm: 0,
            precip_in: 0,
            humidity: 67,
            cloud: 35,
            feelslike_c: 3.8,
            feelslike_f: 38.8,
            windchill_c: 3.8,
            windchill_f: 38.8,
            heatindex_c: 3.8,
            heatindex_f: 38.8,
            dewpoint_c: -1.8,
            dewpoint_f: 28.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.8,
            gust_kph: 2.9,
            uv: 1
          },
          {
            time_epoch: 1672412400,
            time: "2022-12-30 20:00",
            temp_c: 3.2,
            temp_f: 37.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 99,
            wind_dir: "E",
            pressure_mb: 1035,
            pressure_in: 30.58,
            precip_mm: 0,
            precip_in: 0,
            humidity: 68,
            cloud: 36,
            feelslike_c: 3.2,
            feelslike_f: 37.8,
            windchill_c: 3.2,
            windchill_f: 37.8,
            heatindex_c: 3.2,
            heatindex_f: 37.8,
            dewpoint_c: -2.2,
            dewpoint_f: 28,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.7,
            gust_kph: 4.3,
            uv: 1
          },
          {
            time_epoch: 1672416000,
            time: "2022-12-30 21:00",
            temp_c: 3.2,
            temp_f: 37.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 105,
            wind_dir: "ESE",
            pressure_mb: 1035,
            pressure_in: 30.57,
            precip_mm: 0,
            precip_in: 0,
            humidity: 68,
            cloud: 31,
            feelslike_c: 3.2,
            feelslike_f: 37.8,
            windchill_c: 3.2,
            windchill_f: 37.8,
            heatindex_c: 3.2,
            heatindex_f: 37.8,
            dewpoint_c: -2.1,
            dewpoint_f: 28.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 1
          },
          {
            time_epoch: 1672419600,
            time: "2022-12-30 22:00",
            temp_c: 3,
            temp_f: 37.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 99,
            wind_dir: "E",
            pressure_mb: 1035,
            pressure_in: 30.56,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 29,
            feelslike_c: 2.7,
            feelslike_f: 36.9,
            windchill_c: 2.7,
            windchill_f: 36.9,
            heatindex_c: 3,
            heatindex_f: 37.4,
            dewpoint_c: -2.2,
            dewpoint_f: 28,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 1
          },
          {
            time_epoch: 1672423200,
            time: "2022-12-30 23:00",
            temp_c: 2.8,
            temp_f: 37,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 97,
            wind_dir: "E",
            pressure_mb: 1035,
            pressure_in: 30.55,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 50,
            feelslike_c: 2.5,
            feelslike_f: 36.5,
            windchill_c: 2.5,
            windchill_f: 36.5,
            heatindex_c: 2.8,
            heatindex_f: 37,
            dewpoint_c: -2.2,
            dewpoint_f: 28,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 1
          }
        ]
      }
    ]
  }
}


ff.forecast.forecastday.forEach(e => console.log(e.date))